version: '3.8'

services:
  ddos-model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddos-model
    ports:
      - "${MODEL_PORT:-8080}:8080"
    volumes:
      - ./ddos_model.keras:/app/ddos_model.keras
    environment:
      - MODEL_PORT=${MODEL_PORT:-8080}
      - MODEL_HOST=${MODEL_HOST:-0.0.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G  # Adjust based on your model size
        reservations:
          memory: 2G